### ISSUE TITLE
Pinta 2.0 is released. 

### ISSUE THREAD

**Issue by Abhinav1217** [area-of-dev/Pinta.AppImage#1]
Pinta 2.0 is released. It has gtk3 as dependencies. I really need its Appimage because solus os still has old 1.7 in its repos. 

How can I contribute ? I have never built Appimage before but I want to understand and help maintaining here. I have been using a lot of Appimages from your website for so long.

**Comment by AlexWoroschilow** [comment]
Hi, you can take a look at the makefile here:
https://github.com/area-of-dev/Pinta.AppImage/blob/master/Makefile

that is how the AppImage for Pinta is build now. Try to checkout the repository and run `make `
you will probably see some error reports about missed libraries, install them and try again until you have the AppImage. 

After that you can change the Makefile and make it work with Pinta 2.0 and make the PR when you are done. 

As an alternative you can wait for a while, the upgrade for the Pinta is on my todo list :)

**Comment by Abhinav1217** [comment]
I can see Make file downloads a lot of rpm packages, Currently My daily driver is Solus OS. I also have Manjaro installed on a spare laptop. Solus doesn't have rpm2cpio, Is there a solus/ manjaro/ platform neutral, alternative to this?

Do I need to install fedora? 
Can this script work with some kind of docker images or virtual machine? 
Which OS would be best for building appimages? 
I should also have elementary os on some pendrive somewhere. Will this work on Live Session?

Sorry for so many questions, I want to learn packaging applications. I would like to contribute on this, and on many more apps that you have here, as this would be a good learning experience.

**Comment by AlexWoroschilow** [comment]
> I can see Make file downloads a lot of rpm packages, Currently My daily driver is Solus OS. I also have Manjaro installed on a spare laptop. Solus doesn't have rpm2cpio, Is there a solus/ manjaro/ platform neutral, alternative to this?

There is no need in distro hopping. You can make it works under pretty much every linux distro. Regarding rpm2cpio, yes you need to be able to unpack the rpms. 

> Do I need to install fedora?

no, that's not necessary


> Can this script work with some kind of docker images or virtual machine?

sure, the docker image is just another linux environment, it will work there without any problems. 


> Which OS would be best for building appimages?

The best OS for you is the OS you know the best. My advice here would be to pick one distro and stick with it for a while to become a power user. 


However if you have plans to make  your AppImage publicly available, i might make sens to build them using the oldest still supported LTS releases of CentOs or Ubuntu. The good point to start is always the official AppImage documentation, which can be found here: 
https://docs.appimage.org/packaging-guide/



> I should also have elementary os on some pendrive somewhere. Will this work on Live Session?

Sure, but  only if it is not too old.

**Comment by Abhinav1217** [comment]
I have downloaded the release, and currently when trying to run it, I am getting following errors

```
abhinav@abhinav-sol ~/Application/AppImage/bin $ ./Pinta.AppImage
Unhandled exception. System.TypeInitializationException: The type initializer for 'Gtk.Application' threw an exception.
 ---> System.DllNotFoundException: Gtk: libgtk-3-0.dll, libgtk-3.so.0, libgtk-3.0.dylib, gtk-3.dll
   at GLibrary.Load(Library library)
   at Gtk.Application..cctor()
   --- End of inner exception stack trace ---
   at Gtk.Application.Init()
   at Pinta.MainClass.Main(String[] args)
Aborted (core dumped)
```

I have checked and libgtk-3 is installed in my system.

**Comment by AlexWoroschilow** [comment]
updated to 2.1
